version: "3.7"


services:
  vault:
    image: vault:1.10.0
    environment:
      SKIP_SETCAP: 1
      VAULT_DEV_ROOT_TOKEN_ID: dev-root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
